name: Security Scan - SAST & SCA

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  sast-sca-scan:
    runs-on: ubuntu-latest
    name: Run SAST and SCA Scans

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ---------- SAST SCAN USING SEMGREP ----------
    - name: Set up Python (Semgrep)
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run SAST Scan (Semgrep)
      run: semgrep --config auto --exclude node_modules
      continue-on-error: true

    # ---------- SCA FOR JAVASCRIPT (npm audit) ----------
    - name: Run SCA for JS (npm audit)
      run: |
        if [ -f "package.json" ]; then
          npm install --legacy-peer-deps
          npm audit --production --audit-level=high
        else
          echo "No package.json found, skipping JS SCA"
        fi
      continue-on-error: true

    # ---------- SCA FOR PYTHON (safety) ----------
    - name: Install safety for Python SCA
      run: |
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
          pip install safety
          safety check || true
        else
          echo "No requirements.txt found, skipping Python SCA"
        fi
      continue-on-error: true

    # ---------- SCA FOR PHP (composer audit) ----------
    - name: PHP Audit with Composer
      run: |
        if [ -f "composer.json" ]; then
          sudo apt install php-cli unzip curl -y
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install
          php composer.phar audit || true
        else
          echo "No composer.json found, skipping PHP SCA"
        fi
      continue-on-error: true

    # ---------- SCA FOR .NET (dotnet list package) ----------
    - name: .NET Dependency Check
      run: |
        FILES=$(ls *.csproj 2>/dev/null | wc -l)
        if [ "$FILES" -gt 0 ]; then
          dotnet restore
          dotnet list package --vulnerable || true
        else
          echo "No .csproj files found, skipping .NET SCA"
        fi
      continue-on-error: true
