name: Security Scan - SAST & SCA Summary

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  sast-sca-scan:
    runs-on: ubuntu-latest
    name: Run SAST and SCA Scans

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Semgrep and safety
      run: |
        pip install semgrep safety

    # ---------- SAST SCAN ----------
    - name: Run Semgrep (SAST)
      run: |
        echo "🔍 Running Semgrep..."
        semgrep --config auto --exclude node_modules --json > semgrep_output.json || true

    # ---------- JS Dependency Scan ----------
    - name: Run npm audit (SCA)
      run: |
        echo "🔍 Checking npm packages..."
        if [ -f "package.json" ]; then
          npm install --legacy-peer-deps
          npm audit --json > npm_audit.json || true
        else
          echo "No package.json found, skipping JS audit" > npm_audit.json
        fi

    # ---------- Python Dependency Scan ----------
    - name: Run safety check (SCA)
      run: |
        echo "🔍 Checking Python packages..."
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
          safety check --json > safety_output.json || true
        else
          echo "[]" > safety_output.json
        fi

    # ---------- Summary Report ----------
    - name: 📋 Display Summary of Vulnerabilities
      run: |
        echo "=============================="
        echo "🔐 Security Scan Summary"
        echo "=============================="

        echo ""
        echo "▶️ Semgrep Issues:"
        if [ -s semgrep_output.json ]; then
          jq -r '.results[] | "- [\(.check_id)] \(.path):\(.start.line) \(.extra.message)"' semgrep_output.json || echo "No issues found."
        else
          echo "No issues found or scan failed."
        fi

        echo ""
        echo "▶️ npm audit Issues:"
        if [ -s npm_audit.json ]; then
          jq -r '.advisories[]? | "- [\(.module_name)] \(.title)"' npm_audit.json || echo "No vulnerabilities found."
        else
          echo "No package.json or no vulnerabilities."
        fi

        echo ""
        echo "▶️ Python safety Issues:"
        jq -r '.[] | "- [\(.package_name)] \(.issue_severity): \(.description)"' safety_output.json || echo "No Python vulnerabilities."

        echo ""
        echo "✅ Security scan complete."
      continue-on-error: true

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-reports
        path: |
          semgrep_output.json
          npm_audit.json
          safety_output.json
